#!/usr/bin/env perl

`./configure` if(-e phase1 || -e phase2);
my @test_list = glob("test/*");

foreach my $test (@test_list)
{
  print "\n\n".$test . ":\n";

  `./phase2 $test out.o`;
  my @result = `./phase1 -a out.o`;
  foreach my $output (@result)
  {
    print $output;
  }
}

