#!/usr/bin/env perl

`./configure` if(-e phase1 || -e phase2);
my @test_list = glob("test/*");

`rm out.o` if(-e out.o);

foreach my $test (@test_list){
	print "\n\n".$test . ":\n";

 my $error = 0;

	my @result = `./phase2 $test out.o`;
	foreach my $output (@result){
		print $output;
	}
	if (not defined @result[0]){
		my @result = `./phase1 -s out.o`;
		foreach my $output (@result){
			print $output;
    }
	}
}

